### ISSUE TITLE
Windows Server 2016, Powershell console

### ISSUE THREAD

**Issue by BananaAcid** [brunolm/nvm#3]
I could install the PS-module, but not use it.

    PS C:\Users\Administrator> $PSVersionTable.PSVersion

    Major  Minor  Build  Revision
    -----  -----  -----  --------
    5      1      14393  1944

    PS C:\Users\Administrator> nvm install latest
    Installing...

    version : v10.7.0
    npm     : 6.1.0
    v8      : 6.7.288.49
    date    : 2018-07-18

    Unable to find type [System.IO.Compression.ZipFile].
    At C:\Program Files\WindowsPowerShell\Modules\power-nvm\0.3.2\power-nvm.psm1:5 char:5
    +     [System.IO.Compression.ZipFile]::ExtractToDirectory($zipfile, $ou ...
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidOperation: (System.IO.Compression.ZipFile:TypeName) [], RuntimeException
        + FullyQualifiedErrorId : TypeNotFound

    Cannot index into a null array.
    At C:\Program Files\WindowsPowerShell\Modules\power-nvm\0.3.2\power-nvm.psm1:188 char:5
    +     $targetDir = (Join-Path $folder[0].Parent.FullName $versionToInst ...
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
        + FullyQualifiedErrorId : NullArray

    Test-Path : Cannot bind argument to parameter 'Path' because it is null.
    At C:\Program Files\WindowsPowerShell\Modules\power-nvm\0.3.2\power-nvm.psm1:190 char:19
    +     if (Test-Path $targetDir) {
    +                   ~~~~~~~~~~
        + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
        + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom
       mand

    Cannot index into a null array.
    At C:\Program Files\WindowsPowerShell\Modules\power-nvm\0.3.2\power-nvm.psm1:194 char:5
    +     Move-Item $folder[0].FullName $targetDir;
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
        + FullyQualifiedErrorId : NullArray

    PS C:\Users\Administrator>

**Comment by BananaAcid** [comment]
A fix:

Always run `Add-Type -AssemblyName System.IO.Compression.FileSystem` before, so the `nvm` command works.

**Comment by brunolm** [comment]
Should be fixed now in v1.0.1
https://www.powershellgallery.com/packages/power-nvm/1.0.1

You can also install 7z. If you have `7z.exe` on path it will use it instead, it's faster.
